"""SQLAlchemy Core schema for scheduled DNS changes.

Stores only intent (what to do, when) — never zone state.
DNS remains the sole source of truth for what a zone contains.

One metadata definition drives DDL for both supported backends (SQLite and
PostgreSQL) and is the autogenerate source for the Alembic migrations in
``scheduler/migrations/``.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    Column,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Table,
    Text,
    true,
)
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP
from sqlalchemy.engine import Dialect
from sqlalchemy.types import TypeDecorator

# Explicit names for constraints Alembic would otherwise have to invent, so
# autogenerated migrations stay stable and SQLite batch operations can find them.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UtcDateTime(TypeDecorator[datetime]):
    """Timezone-aware UTC timestamp that is portable across both backends.

    PostgreSQL gets a native ``timestamptz`` so the columns are usable from
    psql and ordinary SQL tooling. SQLite has no timezone-aware type, so values
    are stored as normalised ISO-8601 UTC strings, which compare and sort
    chronologically as plain text.
    """

    impl = Text
    cache_ok = True

    def load_dialect_impl(self, dialect: Dialect) -> Any:
        if dialect.name == "postgresql":
            return dialect.type_descriptor(TIMESTAMP(timezone=True))
        return dialect.type_descriptor(Text())

    def process_bind_param(self, value: datetime | None, dialect: Dialect) -> Any:
        if value is None:
            return None
        if not isinstance(value, datetime):
            raise TypeError(f"UtcDateTime requires a datetime, got {type(value).__name__}")
        if value.tzinfo is None:
            value = value.replace(tzinfo=UTC)
        value = value.astimezone(UTC)
        if dialect.name == "postgresql":
            return value
        return value.isoformat()

    def process_result_value(self, value: Any, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        dt = value if isinstance(value, datetime) else datetime.fromisoformat(value)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=UTC)
        return dt.astimezone(UTC)


def json_column() -> Any:
    """JSON column type: JSONB on PostgreSQL, serialised text on SQLite.

    ``none_as_null`` keeps ``None`` as a SQL NULL rather than the JSON encoding
    of ``null``, so absent values stay distinguishable from stored nulls.
    """
    return JSON(none_as_null=True).with_variant(JSONB(none_as_null=True), "postgresql")


def autoincrement_pk() -> Any:
    """Surrogate key type: identity on PostgreSQL, rowid alias on SQLite.

    SQLite only auto-assigns for ``INTEGER PRIMARY KEY``; a ``BIGINT`` primary
    key is not a rowid alias and would not autoincrement.
    """
    return BigInteger().with_variant(Integer(), "sqlite")


scheduled_changes = Table(
    "scheduled_changes",
    metadata,
    Column("id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("description", Text),
    Column("zone", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("scheduled_at", UtcDateTime),
    Column("not_valid_after", UtcDateTime),
    Column("auto_prerequisites", Boolean, nullable=False, server_default=true()),
    Column("created_at", UtcDateTime, nullable=False),
    Column("created_by", Text),
    Column("updated_at", UtcDateTime, nullable=False),
    Column("attempts", Integer, nullable=False, server_default="0"),
    Column("next_attempt_at", UtcDateTime),
    Column("last_error", Text),
    Column("applied_at", UtcDateTime),
    Column("result_rcode", Text),
    Column("new_serial", BigInteger),
    Column("reverted_at", UtcDateTime),
    Column("lease_owner", Text),
    Column("lease_expires_at", UtcDateTime),
    Column("source", Text, nullable=False, server_default="scheduler"),
    Index("idx_scheduled_changes_status", "status"),
    Index("idx_scheduled_changes_zone", "zone"),
    Index("idx_scheduled_changes_due", "status", "scheduled_at"),
    Index("idx_scheduled_changes_source", "source"),
    Index("idx_scheduled_changes_retention", "status", "updated_at"),
)

scheduled_operations = Table(
    "scheduled_operations",
    metadata,
    Column(
        "change_id",
        Text,
        ForeignKey("scheduled_changes.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("seq", Integer, primary_key=True),
    Column("action", Text, nullable=False),
    Column("name", Text, nullable=False),
    Column("type", Text, nullable=False),
    Column("rdclass", Text, nullable=False, server_default="IN"),
    Column("ttl", Integer, nullable=False, server_default="3600"),
    Column("records", json_column()),
    Column("prior_ttl", Integer),
    Column("prior_records", json_column()),
    Column("snapshot_at", UtcDateTime),
)

scheduled_prerequisites = Table(
    "scheduled_prerequisites",
    metadata,
    Column(
        "change_id",
        Text,
        ForeignKey("scheduled_changes.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("seq", Integer, primary_key=True),
    Column("prereq_type", Text, nullable=False),
    Column("name", Text, nullable=False),
    Column("rdtype", Text),
    Column("rdclass", Text, nullable=False, server_default="IN"),
    Column("data", Text),
)

scheduled_change_events = Table(
    "scheduled_change_events",
    metadata,
    Column("id", autoincrement_pk(), primary_key=True, autoincrement=True),
    Column(
        "change_id",
        Text,
        ForeignKey("scheduled_changes.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("ts", UtcDateTime, nullable=False),
    Column("event", Text, nullable=False),
    Column("actor", Text),
    Column("detail", json_column()),
    Index("idx_scheduled_change_events_change", "change_id"),
    Index("idx_scheduled_change_events_event", "event"),
    Index("idx_scheduled_change_events_actor", "actor"),
)

# Newest-first audit listing is the hot query, so index the sort order.
Index(
    "idx_scheduled_change_events_ts",
    scheduled_change_events.c.ts.desc(),
)

__all__ = [
    "UtcDateTime",
    "autoincrement_pk",
    "json_column",
    "metadata",
    "scheduled_change_events",
    "scheduled_changes",
    "scheduled_operations",
    "scheduled_prerequisites",
]
