when:
  - event: cron
    cron: renovate

steps:
  renovate:
    image: ghcr.io/renovatebot/renovate:full
    environment:
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ENDPOINT: https://codeberg.org/api/v1
      RENOVATE_TOKEN:
        from_secret: renovate_token
      RENOVATE_REPOSITORIES: davidgroves/dns-zone-manager
      LOG_LEVEL: info
    commands:
      - renovate
